#@ load("@ytt:data", "data")
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: acme-fitness-gateway
spec:
  service:
    type: ClusterIP
  api:
    title: ACME Fitness API Gateway
    description: The entrypoint for all things ACME Fitness
    version: 1.0.0
    serverUrl: #@ "https://acme-fitness.apps.{}".format(data.values.ingress.domain)
  env:
    - name: spring.cloud.gateway.httpclient.connect-timeout
      value: "90"
  sso:
    secret: acme-fitness-client-registration
